---

- name: force inactive users to logout
  template:
    src: timeout_shell.j2
    dest: /etc/profile.d/timout_shell.sh

- name: install the monitoring script
  template:
    src: monitor_script.j2
    dest: /usr/local/bin/ondemand_server_monitor
    mode: 0755
    owner: root
    group: root

- name: install systemd service unit and timer
  copy:
    src: "systemd_{{ item }}"
    dest: "/etc/systemd/system/ondemand_server.{{ item }}"
  with_items:
    - service
    - timer

- name: enable our service
  systemd:
    daemon_reload: yes
    name: ondemand_server.timer
    enabled: yes
    state: started


