---

- name: install the monitoring script
  template:
    src: monitor_script.j2
    dest: /usr/local/bin/shutdown_on_idle_monitor
    mode: 0755
    owner: root
    group: root

- name: install systemd service unit and timer
  copy:
    src: "systemd_{{ item }}"
    dest: "/etc/systemd/system/shutdown_on_idle.{{ item }}"
  with_items:
    - service
    - timer

- name: enable our service
  systemd:
    daemon_reload: yes
    name: shutdown_on_idle.timer
    enabled: yes
    state: started


